### ISSUE TITLE
TODO List for v1.3.6

### ISSUE THREAD

**Issue by stevezhengshiqi** [daliansky/XiaoMi-Pro-Hackintosh#235]
This is a TODO list for next release v1.3.6 or in the future. Because my device was physically damaged and it was sent back to my homeland for repairing, I may not contribute more to this repository. I hope someone can take over this repository and finish the following things:

- [x] Update Lilu and its plugins (only use release version)
  - No SMCLightSensor, SuperIO, VoodooPS2Mouse, and VoodooPS2Trackpad
  - Modify VoodooPS2 as https://github.com/daliansky/XiaoMi-Pro-Hackintosh/commit/2a3739eea1e97babc6928a1237a281c0f47375f3 and https://github.com/daliansky/XiaoMi-Pro-Hackintosh/commit/a4309ba4d1cda06db37f7b48632e648d3d17e877
- [x] Update OpenCore and its config.plist (only use release version; config refers to https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Sample.plist)
- [x] Update Clover
  - Only need updates on `BOOTX64.efi`, `CLOVERX64.efi`, `FSInject.efi`, `AudioDxe.efi`, and `tools` folder
  - No new folders, keep directory clean
- [x] Inject Clover's default SerialNumber and BoardSerialNumber to OpenCore's config 
  - Clover's SerialNumber = PlatformInfo - Generic - SystemSerialNumber, 
Clover's BoardSerialNumber = PlatformInfo - Generic - MLB)
- [x] Add `complete-modeset-framebuffers` property to enforce complete IGPU modeset on con0 or con1(I am not sure); otherwise, the internal screen turns black after connecting to the left HDMI port
- [ ] Wait until [VoodooInput](https://github.com/kprinssu/VoodooInput) and [VoodooInputEngine](https://github.com/kprinssu/VoodooInputEngine/commit/5a2ccb27d19b20830e5044468620acaf3bfa4dac) finish. VoodooPS2 will also use VoodooInput as its interface

ATTENTION: Never use `Clover Configurator` or `OC Configurator` to edit config.plist. They will mess up the format.

**Comment by Alkanna** [comment]
Made a pr for clover update. #236
